backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'tag'
    label: 'Tag'
    format: 'json'
    folder: 'assets/content/tag'
    create: true
    slug: '{{fields.title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
  - name: 'portfolio'
    label: 'Portfolio'
    format: 'json'
    folder: 'assets/content/portfolio'
    create: true
    identifier_field: 'slug'
    slug: '{{fields.slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Featured', name: 'featured', widget: 'boolean', required: false }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Tags', name: 'tags', widget: 'relation', multiple: true, searchFields: ['title'], collection: 'tag', valueField: 'title' }
  - label: "Page"
    name: "page"
    files:
      - label: "Home Page"
        name: "home"
        file: "assets/content/page/home.json"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "intro", widget: "markdown"}
          - label: "Header"
            name: "header"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
          - label: "Stakes"
            name: "stakes"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
          - label: "Value"
            name: "value"
            widget: "list"
            fields:
              - {label: "Pretitle", name: "pretitle", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - label: "Propositions"
                name: "propositions"
                widget: "list"
                field:
                  name: "proposition"
                  label: "Proposition"
                  widget: "list"
                  fields:
                    - {label: "Title", name: "title", widget: "string"}
                    - {label: "Text", name: "text", widget: "string"}
                    - name: "icon"
                      label: "Icon"
                      widget: "list"
                      fields:
                        - {label: "Type", name: "type", widget: "string"}
                        - {label: "Name", name: "name", widget: "string"}
                        - {label: "Margin", name: "margin", widget: "string"}
          - label: "Guide"
            name: "guide"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
          - label: "Plan"
            name: "plan"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - {label: "Bottom", name: "bottom", widget: "string"}
              - label: "Steps"
                name: "steps"
                widget: "list"
                field: 
                  name: "step"
                  label: "Step"
                  widget: "list"
                  fields:
                    - {label: "Title", name: "title", widget: "string"}
                    - {label: "Text", name: "text", widget: "string"}
                    - name: "icon"
                      label: "Icon"
                      widget: "list"
                      fields:
                        - {label: "Type", name: "type", widget: "string"}
                        - {label: "Name", name: "name", widget: "string"}
                        - {label: "Margin", name: "margin", widget: "string"}
      - label: "Home Page 2"
          name: "home2"
          file: "assets/content/page/home2.json"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "intro", widget: "markdown"}
            - label: "Header"
              name: "header"
              widget: "list"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Subtitle", name: "subtitle", widget: "string"}
            - label: "Stakes"
              name: "stakes"
              widget: "list"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Subtitle", name: "subtitle", widget: "string"}
            - label: "Value"
              name: "value"
              widget: "list"
              fields:
                - {label: "Pretitle", name: "pretitle", widget: "string"}
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Subtitle", name: "subtitle", widget: "string"}
                - label: "Propositions"
                  name: "propositions"
                  widget: "list"
                  field:
                    name: "proposition"
                    label: "Proposition"
                    widget: "list"
                    fields:
                      - {label: "Title", name: "title", widget: "string"}
                      - {label: "Text", name: "text", widget: "string"}
                      - name: "icon"
                        label: "Icon"
                        widget: "list"
                        fields:
                          - {label: "Type", name: "type", widget: "string"}
                          - {label: "Name", name: "name", widget: "string"}
                          - {label: "Margin", name: "margin", widget: "string"}
            - label: "Guide"
              name: "guide"
              widget: "list"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Subtitle", name: "subtitle", widget: "string"}
            - label: "Plan"
              name: "plan"
              widget: "list"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Subtitle", name: "subtitle", widget: "string"}
                - {label: "Bottom", name: "bottom", widget: "string"}
                - label: "Steps"
                  name: "steps"
                  widget: "list"
                  field: 
                    name: "step"
                    label: "Step"
                    widget: "list"
                    fields:
                      - {label: "Title", name: "title", widget: "string"}
                      - {label: "Text", name: "text", widget: "string"}
                      - name: "icon"
                        label: "Icon"
                        widget: "list"
                        fields:
                          - {label: "Type", name: "type", widget: "string"}
                          - {label: "Name", name: "name", widget: "string"}
                          - {label: "Margin", name: "margin", widget: "string"}
