[[redirects]]
  from = "/portfolio"
  to = "/referenzen/"
  status = 301

[[redirects]]
  from = "/google-ads"
  to = "/leistungen/google-werbung/"
  status = 301

[[redirects]]
  from = "/leistungen/google-ads"
  to = "/leistungen/google-werbung/"
  status = 301

[[redirects]]
  from = "/webseiten"
  to = "/leistungen/webseiten/"
  status = 301

[[redirects]]
  from = "/cms-systeme"
  to = "/leistungen/cms-systeme/"
  status = 301

[[redirects]]
  from = "/leistungen"
  to = "/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[plugins]]
  package = "@netlify/plugin-sitemap"
